### PR TITLE
Python 3 related fixes 

### PR DESCRIPTION
**Pull request by jan-janssen**
I started to integrate tamkin to conda-forge and noticed some parts are not yet Python3 compatible 
https://github.com/conda-forge/staged-recipes/pull/9429

### CODE REVIEW

**Comment by tovrstra** [comment]
I agree. There are probably more python 3 issues that need to be fixed. It is on my list for a while but I did not manage yet to get started with it.

**Comment by jan-janssen** [comment]
After adding the brackets for the print statements at least the import with Python 3 works.

**Comment by jan-janssen** [comment]
@tovrstra the code should be python 3 ready, but I was not able to extend the test environment. Maybe you can take a look at this?

**Comment by tovrstra** [comment]
@jan-janssen Thanks for all these fixes already and apologies for the delay. Our CI setup is not great at the moment and should be replaced by something less fragile. In any case, your changes look good and I'll merge in a second.

**Comment by jan-janssen** [comment]
@tovrstra Is it possible to release a new version on pypi - 1.2.5 ? Then I can continue working on the integration with conda-forge.

**Comment by tovrstra** [comment]
sure. It's on its way.

**Comment by tovrstra** [comment]
That release was created and when CI passes, it will automatically upload the release files.

**Comment by tovrstra** [comment]
@jan-janssen Can you try release 1.2.6. This one should fully work on py3, including passing unit tests. I also did some additional cleanups.

**Comment by jan-janssen** [comment]
@tovrstra Can you comment on https://github.com/conda-forge/staged-recipes/pull/9429 then I can add you as a maintainer to the conda-forge recipe?

**Pull request merged**
